name: CI

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4
        with:
          node-version: "20"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Diff openapi.json with main
        id: diff_openapi
        run: |
          git fetch origin main
          if git diff --quiet origin/main -- ./openapi.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Java
        if: steps.diff_openapi.outputs.changed == 'true'
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Generate client
        if: steps.diff_openapi.outputs.changed == 'true'
        run: yarn gen-client

      - name: Normalize list enums
        run: yarn normalize-list-enums

      - name: Setup Copywrite
        uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 #v1.1.3

      - name: Add copyright headers
        run: copywrite headers

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 #v5
        with:
          commit_message: "auto: generated client updates"

      - name: Type-check ts files
        run: yarn lint
